# Generated by Django 3.2.13 on 2022-09-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220924_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='show',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='show',
            new_name='available',
        ),
    ]
