# Generated by Django 3.2.13 on 2023-04-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230415_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategory',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
