# Generated by Django 3.2.13 on 2023-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_subsubcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
