# Generated by Django 3.2.13 on 2023-04-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productvariation_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='image',
        ),
    ]
