# Generated by Django 3.2.13 on 2022-09-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220924_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='variation',
        ),
    ]
