# Generated by Django 3.2.13 on 2022-09-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20220929_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_paid',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
