# Generated by Django 3.2.13 on 2023-04-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220925_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['product__slug']},
        ),
    ]
