# Generated by Django 3.2.13 on 2022-09-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('order', '0002_auto_20220924_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'CREATED'), ('P', 'PAID_TO_DELIEVER'), ('D', 'DELIVERED')], default=22, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
